insert into Countries (Name) values ('Afghanistan')
insert into Countries (Name) values ('Aland')
insert into Countries (Name) values ('Albania')
insert into Countries (Name) values ('Algeria')
insert into Countries (Name) values ('American Samoa')
insert into Countries (Name) values ('Andorra')
insert into Countries (Name) values ('Angola')
insert into Countries (Name) values ('Antarctica')
insert into Countries (Name) values ('Antigua and Barbuda')
insert into Countries (Name) values ('Argentina')
insert into Countries (Name) values ('Armenia')
insert into Countries (Name) values ('Aruba')
insert into Countries (Name) values ('Australia')
insert into Countries (Name) values ('Austria')
insert into Countries (Name) values ('Azerbaijan')
insert into Countries (Name) values ('Bahrain')
insert into Countries (Name) values ('Bangladesh')
insert into Countries (Name) values ('Barbados')
insert into Countries (Name) values ('Belarus')
insert into Countries (Name) values ('Belgium')
insert into Countries (Name) values ('Belize')
insert into Countries (Name) values ('Benin')
insert into Countries (Name) values ('Bermuda')
insert into Countries (Name) values ('Bhutan')
insert into Countries (Name) values ('Bolivia')
insert into Countries (Name) values ('Bosnia and Herzegovina')
insert into Countries (Name) values ('Botswana')
insert into Countries (Name) values ('Brazil')
insert into Countries (Name) values ('Brunei')
insert into Countries (Name) values ('Bulgaria')
insert into Countries (Name) values ('Burkina Faso')
insert into Countries (Name) values ('Burundi')
insert into Countries (Name) values ('Cambodia')
insert into Countries (Name) values ('Cameroon')
insert into Countries (Name) values ('Canada')
insert into Countries (Name) values ('Cape Verde')
insert into Countries (Name) values ('Cayman Islands')
insert into Countries (Name) values ('Central African Republic')
insert into Countries (Name) values ('Chad')
insert into Countries (Name) values ('Chile')
insert into Countries (Name) values ('China')
insert into Countries (Name) values ('Colombia')
insert into Countries (Name) values ('Comoros')
insert into Countries (Name) values ('Congo (Brazzaville)')
insert into Countries (Name) values ('Congo (Kinshasa)')
insert into Countries (Name) values ('Cook Islands')
insert into Countries (Name) values ('Costa Rica')
insert into Countries (Name) values ('Croatia')
insert into Countries (Name) values ('Cuba')
insert into Countries (Name) values ('Curacao')
insert into Countries (Name) values ('Cyprus')
insert into Countries (Name) values ('Czech Republic')
insert into Countries (Name) values ('Denmark')
insert into Countries (Name) values ('Djibouti')
insert into Countries (Name) values ('Dominica')
insert into Countries (Name) values ('Dominican Republic')
insert into Countries (Name) values ('East Timor')
insert into Countries (Name) values ('Ecuador')
insert into Countries (Name) values ('Egypt')
insert into Countries (Name) values ('El Salvador')
insert into Countries (Name) values ('Equatorial Guinea')
insert into Countries (Name) values ('Eritrea')
insert into Countries (Name) values ('Estonia')
insert into Countries (Name) values ('Ethiopia')
insert into Countries (Name) values ('Falkland Islands')
insert into Countries (Name) values ('Faroe Islands')
insert into Countries (Name) values ('Federated States of Micronesia')
insert into Countries (Name) values ('Fiji')
insert into Countries (Name) values ('Finland')
insert into Countries (Name) values ('France')
insert into Countries (Name) values ('French Polynesia')
insert into Countries (Name) values ('Gabon')
insert into Countries (Name) values ('Georgia')
insert into Countries (Name) values ('Germany')
insert into Countries (Name) values ('Ghana')
insert into Countries (Name) values ('Gibraltar')
insert into Countries (Name) values ('Greece')
insert into Countries (Name) values ('Greenland')
insert into Countries (Name) values ('Grenada')
insert into Countries (Name) values ('Guam')
insert into Countries (Name) values ('Guatemala')
insert into Countries (Name) values ('Guinea')
insert into Countries (Name) values ('Guinea Bissau')
insert into Countries (Name) values ('Guyana')
insert into Countries (Name) values ('Haiti')
insert into Countries (Name) values ('Honduras')
insert into Countries (Name) values ('Hong Kong S.A.R.')
insert into Countries (Name) values ('Hungary')
insert into Countries (Name) values ('Iceland')
insert into Countries (Name) values ('India')
insert into Countries (Name) values ('Indonesia')
insert into Countries (Name) values ('Iran')
insert into Countries (Name) values ('Iraq')
insert into Countries (Name) values ('Ireland')
insert into Countries (Name) values ('Isle of Man')
insert into Countries (Name) values ('Israel')
insert into Countries (Name) values ('Italy')
insert into Countries (Name) values ('Ivory Coast')
insert into Countries (Name) values ('Jamaica')
insert into Countries (Name) values ('Japan')
insert into Countries (Name) values ('Jordan')
insert into Countries (Name) values ('Kazakhstan')
insert into Countries (Name) values ('Kenya')
insert into Countries (Name) values ('Kiribati')
insert into Countries (Name) values ('Kosovo')
insert into Countries (Name) values ('Kuwait')
insert into Countries (Name) values ('Kyrgyzstan')
insert into Countries (Name) values ('Laos')
insert into Countries (Name) values ('Latvia')
insert into Countries (Name) values ('Lebanon')
insert into Countries (Name) values ('Lesotho')
insert into Countries (Name) values ('Liberia')
insert into Countries (Name) values ('Libya')
insert into Countries (Name) values ('Liechtenstein')
insert into Countries (Name) values ('Lithuania')
insert into Countries (Name) values ('Luxembourg')
insert into Countries (Name) values ('Macau S.A.R')
insert into Countries (Name) values ('Macedonia')
insert into Countries (Name) values ('Madagascar')
insert into Countries (Name) values ('Malawi')
insert into Countries (Name) values ('Malaysia')
insert into Countries (Name) values ('Maldives')
insert into Countries (Name) values ('Mali')
insert into Countries (Name) values ('Malta')
insert into Countries (Name) values ('Marshall Islands')
insert into Countries (Name) values ('Mauritania')
insert into Countries (Name) values ('Mauritius')
insert into Countries (Name) values ('Mexico')
insert into Countries (Name) values ('Moldova')
insert into Countries (Name) values ('Monaco')
insert into Countries (Name) values ('Mongolia')
insert into Countries (Name) values ('Montenegro')
insert into Countries (Name) values ('Morocco')
insert into Countries (Name) values ('Mozambique')
insert into Countries (Name) values ('Myanmar')
insert into Countries (Name) values ('Namibia')
insert into Countries (Name) values ('Nepal')
insert into Countries (Name) values ('Netherlands')
insert into Countries (Name) values ('New Caledonia')
insert into Countries (Name) values ('New Zealand')
insert into Countries (Name) values ('Nicaragua')
insert into Countries (Name) values ('Niger')
insert into Countries (Name) values ('Nigeria')
insert into Countries (Name) values ('North Korea')
insert into Countries (Name) values ('Northern Cyprus')
insert into Countries (Name) values ('Northern Mariana Islands')
insert into Countries (Name) values ('Norway')
insert into Countries (Name) values ('Oman')
insert into Countries (Name) values ('Pakistan')
insert into Countries (Name) values ('Palau')
insert into Countries (Name) values ('Palestine')
insert into Countries (Name) values ('Panama')
insert into Countries (Name) values ('Papua New Guinea')
insert into Countries (Name) values ('Paraguay')
insert into Countries (Name) values ('Peru')
insert into Countries (Name) values ('Philippines')
insert into Countries (Name) values ('Poland')
insert into Countries (Name) values ('Portugal')
insert into Countries (Name) values ('Puerto Rico')
insert into Countries (Name) values ('Qatar')
insert into Countries (Name) values ('Romania')
insert into Countries (Name) values ('Russia')
insert into Countries (Name) values ('Rwanda')
insert into Countries (Name) values ('Saint Kitts and Nevis')
insert into Countries (Name) values ('Saint Lucia')
insert into Countries (Name) values ('Saint Vincent and the Grenadines')
insert into Countries (Name) values ('Samoa')
insert into Countries (Name) values ('San Marino')
insert into Countries (Name) values ('Sao Tome and Principe')
insert into Countries (Name) values ('Saudi Arabia')
insert into Countries (Name) values ('Senegal')
insert into Countries (Name) values ('Serbia')
insert into Countries (Name) values ('Seychelles')
insert into Countries (Name) values ('Sierra Leone')
insert into Countries (Name) values ('Singapore')
insert into Countries (Name) values ('Slovakia')
insert into Countries (Name) values ('Slovenia')
insert into Countries (Name) values ('Solomon Islands')
insert into Countries (Name) values ('Somalia')
insert into Countries (Name) values ('Somaliland')
insert into Countries (Name) values ('South Africa')
insert into Countries (Name) values ('South Georgia and the Islands')
insert into Countries (Name) values ('South Korea')
insert into Countries (Name) values ('South Sudan')
insert into Countries (Name) values ('Spain')
insert into Countries (Name) values ('Sri Lanka')
insert into Countries (Name) values ('Sudan')
insert into Countries (Name) values ('Suriname')
insert into Countries (Name) values ('Svalbard and Jan Mayen Islands')
insert into Countries (Name) values ('Swaziland')
insert into Countries (Name) values ('Sweden')
insert into Countries (Name) values ('Switzerland')
insert into Countries (Name) values ('Syria')
insert into Countries (Name) values ('Taiwan')
insert into Countries (Name) values ('Tajikistan')
insert into Countries (Name) values ('Tanzania')
insert into Countries (Name) values ('Thailand')
insert into Countries (Name) values ('The Bahamas')
insert into Countries (Name) values ('The Gambia')
insert into Countries (Name) values ('Togo')
insert into Countries (Name) values ('Tonga')
insert into Countries (Name) values ('Trinidad and Tobago')
insert into Countries (Name) values ('Tunisia')
insert into Countries (Name) values ('Turkey')
insert into Countries (Name) values ('Turkmenistan')
insert into Countries (Name) values ('Turks and Caicos Islands')
insert into Countries (Name) values ('Tuvalu')
insert into Countries (Name) values ('Uganda')
insert into Countries (Name) values ('Ukraine')
insert into Countries (Name) values ('United Arab Emirates')
insert into Countries (Name) values ('United Kingdom')
insert into Countries (Name) values ('United States of America')
insert into Countries (Name) values ('United States Virgin Islands')
insert into Countries (Name) values ('Uruguay')
insert into Countries (Name) values ('Uzbekistan')
insert into Countries (Name) values ('Vanuatu')
insert into Countries (Name) values ('Vatican (Holy Sea)')
insert into Countries (Name) values ('Venezuela')
insert into Countries (Name) values ('Vietnam')
insert into Countries (Name) values ('Western Sahara')
insert into Countries (Name) values ('Yemen')
insert into Countries (Name) values ('Zambia')
insert into Countries (Name) values ('Zimbabwe')